service: hola-mundo-serverless 
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  hello_world:
    handler: handler.hello_world
    events:
      - http:
          path: /hello_world
          method: get
  
